pull_request_rules:
  - name: merge when all requested reviews are valid
    conditions:
      - label="ready-to-merge"
    actions:
      comment:
        message: Ready to merge
  - name: Add redirects label if PR body is checked
    conditions:
      - body~=(?m)^- \[X|x\] Add test-label
    actions:
      label:
        add:
            - test-label
  - name: Comment on PR asking for redirects
    conditions:
      - label="test-label"
    actions:
      comment:
        message: |
            @{{author}}, thank you for requesting to the `test-label`!